import type { BaseAdapter } from "../../shared/db/adapters/base.adapter.js";
import type {
  ProjectMonthlySales,
  SaveMonthlySalesPayload,
  BvaSalesAggregate,
} from "../../shared/types/index.js";

const SALES_INSERT_COLS = [
  "project_id", "year", "month",
  "budget_amount", "actual_amount", "projected_amount", "notes", "created_by",
] as const;

const SALES_UPDATE_COLS = [
  "budget_amount", "actual_amount", "projected_amount", "notes", "created_by",
] as const;

const SALES_CONFLICT_COLS = ["project_id", "year", "month"] as const;

const SALES_SELECT = `id,
         project_id AS "projectId",
         year,
         month,
         budget_amount AS "budgetAmount",
         actual_amount AS "actualAmount",
         projected_amount AS "projectedAmount",
         notes,
         created_by AS "createdBy",
         created_at AS "createdAt",
         updated_at AS "updatedAt"`;

export class SalesRepository {
  constructor(private readonly db: BaseAdapter) {}

  async ensureTable(): Promise<void> {
    const isOracle = this.db.placeholder(0) === ":0";

    const createTableSql = isOracle
      ? `CREATE TABLE project_monthly_sales (
          id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
          project_id       NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
          year             NUMBER NOT NULL,
          month            NUMBER NOT NULL CHECK (month BETWEEN 1 AND 12),
          budget_amount    NUMBER(15,2),
          actual_amount    NUMBER(15,2),
          projected_amount NUMBER(15,2),
          notes            CLOB,
          created_by       VARCHAR2(255 CHAR),
          created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
          updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
          CONSTRAINT uq_project_monthly_sales UNIQUE (project_id, year, month)
        )`
      : `CREATE TABLE IF NOT EXISTS project_monthly_sales (
          id               BIGSERIAL PRIMARY KEY,
          project_id       BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
          year             INTEGER NOT NULL,
          month            INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
          budget_amount    NUMERIC(15,2),
          actual_amount    NUMERIC(15,2),
          projected_amount NUMERIC(15,2),
          notes            TEXT,
          created_by       TEXT,
          created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          updated_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT uq_project_monthly_sales UNIQUE (project_id, year, month)
        )`;

    const createIndexSql = `CREATE INDEX idx_monthly_sales_project_year
      ON project_monthly_sales (project_id, year, month)`;

    try {
      await this.db.query(createTableSql);
    } catch (err: unknown) {
      const code = err as { errorNum?: number; code?: string };
      if (code.errorNum !== 955 && code.code !== "42P07") {
        throw err;
      }
    }

    try {
      await this.db.query(createIndexSql);
    } catch (err: unknown) {
      const code = err as { errorNum?: number; code?: string };
      if (code.errorNum !== 955 && code.errorNum !== 1408 && code.code !== "42P07") {
        throw err;
      }
    }
  }

  async getMonthlySales(
    projectId: number,
    year?: number
  ): Promise<ProjectMonthlySales[]> {
    const params: unknown[] = [projectId];
    let yearFilter = "";
    if (typeof year === "number") {
      params.push(year);
      yearFilter = `AND year = ${this.db.placeholder(2)}`;
    }

    const { rows } = await this.db.query<ProjectMonthlySales>(
      `SELECT
         ${SALES_SELECT}
       FROM project_monthly_sales
       WHERE project_id = ${this.db.placeholder(1)}
         ${yearFilter}
       ORDER BY year, month`,
      params
    );
    return rows;
  }

  async saveMonthlySales(payload: SaveMonthlySalesPayload): Promise<ProjectMonthlySales> {
    const result = await this.db.upsertReturning<ProjectMonthlySales>({
      table: "project_monthly_sales",
      conflictCols: [...SALES_CONFLICT_COLS],
      insertCols: [...SALES_INSERT_COLS],
      updateCols: [...SALES_UPDATE_COLS],
      values: [
        payload.projectId,
        payload.year,
        payload.month,
        payload.budgetAmount ?? null,
        payload.actualAmount ?? null,
        payload.projectedAmount ?? null,
        payload.notes ?? null,
        payload.createdBy ?? null,
      ],
      selectExpr: SALES_SELECT,
      extraSetClauses: [`updated_at = ${this.db.nowExpression()}`],
    });
    return result.rows[0];
  }

  async bulkSaveMonthlySales(
    payloads: SaveMonthlySalesPayload[]
  ): Promise<ProjectMonthlySales[]> {
    if (payloads.length > 500) {
      throw new Error("Bulk operations are limited to 500 items");
    }
    if (payloads.length === 0) return [];

    const rows = payloads.map((p) => [
      p.projectId,
      p.year,
      p.month,
      p.budgetAmount ?? null,
      p.actualAmount ?? null,
      p.projectedAmount ?? null,
      p.notes ?? null,
      p.createdBy ?? null,
    ]);

    const result = await this.db.bulkUpsertReturning<ProjectMonthlySales>({
      table: "project_monthly_sales",
      conflictCols: [...SALES_CONFLICT_COLS],
      insertCols: [...SALES_INSERT_COLS],
      updateCols: [...SALES_UPDATE_COLS],
      selectExpr: SALES_SELECT,
      extraSetClauses: [`updated_at = ${this.db.nowExpression()}`],
      rows,
    });

    return result.rows;
  }

  async deleteMonthlySales(
    projectId: number,
    year: number,
    month: number
  ): Promise<boolean> {
    const { rowCount } = await this.db.query(
      `DELETE FROM project_monthly_sales
       WHERE project_id = ${this.db.placeholder(1)}
         AND year = ${this.db.placeholder(2)}
         AND month = ${this.db.placeholder(3)}`,
      [projectId, year, month]
    );
    return rowCount > 0;
  }

  async getBvaSalesAggregate(projectId: number): Promise<BvaSalesAggregate | null> {
    const { rows } = await this.db.query<BvaSalesAggregate>(
      `SELECT
         COALESCE(SUM(budget_amount), 0)    AS "budget",
         COALESCE(SUM(actual_amount), 0)     AS "actual",
         COALESCE(SUM(projected_amount), 0)  AS "projected",
         COALESCE(SUM(
           CASE WHEN actual_amount IS NOT NULL AND actual_amount != 0
                THEN actual_amount
                ELSE COALESCE(projected_amount, 0)
           END
         ), 0) AS "blended",
         MAX(CASE WHEN actual_amount IS NOT NULL OR projected_amount IS NOT NULL
                  THEN updated_at END) AS "lastActivity"
       FROM project_monthly_sales
       WHERE project_id = ${this.db.placeholder(1)}`,
      [projectId]
    );
    if (rows.length === 0) return null;
    return rows[0];
  }

  async clearProjectSales(projectId: number): Promise<number> {
    const { rowCount } = await this.db.query(
      `DELETE FROM project_monthly_sales WHERE project_id = ${this.db.placeholder(1)}`,
      [projectId]
    );
    return rowCount;
  }
}
