CREATE TABLE project_monthly_sales (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_id       NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  year             NUMBER NOT NULL,
  month            NUMBER NOT NULL CHECK (month BETWEEN 1 AND 12),
  budget_amount    NUMBER(15,2),
  actual_amount    NUMBER(15,2),
  projected_amount NUMBER(15,2),
  notes            CLOB,
  created_by       VARCHAR2(255 CHAR),
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_project_monthly_sales UNIQUE (project_id, year, month)
);

CREATE INDEX idx_monthly_sales_project_year
  ON project_monthly_sales (project_id, year, month);
